import type { SourceManifestEntry } from "../types.js";

export const sourceManifest: SourceManifestEntry[] = [
  {
    id: "openai-blog-rss",
    vendor: "openai",
    name: "OpenAI Blog RSS",
    url: "https://openai.com/news/rss.xml",
    parser: "rss_atom",
    defaultCategory: "blog_update",
    cooldownSeconds: 3600,
    description: "OpenAI news and product updates.",
  },
  {
    id: "openai-platform-release-notes-rss",
    vendor: "openai",
    name: "OpenAI Platform Changelog RSS",
    url: "https://platform.openai.com/changelog.rss",
    parser: "rss_atom",
    defaultCategory: "release_note",
    cooldownSeconds: 3600,
    description: "OpenAI platform release notes and changelog posts.",
  },
  {
    id: "openai-github-releases",
    vendor: "openai",
    name: "OpenAI SDK Releases",
    url: "https://github.com/openai/openai-python/releases.atom",
    parser: "github_releases",
    defaultCategory: "model_release",
    cooldownSeconds: 10800,
    description: "Official repository releases for OpenAI SDK components.",
  },
  {
    id: "openai-model-release-notes",
    vendor: "openai",
    name: "OpenAI Model Deprecations",
    url: "https://platform.openai.com/docs/deprecations",
    parser: "changelog_html",
    defaultCategory: "deprecation",
    cooldownSeconds: 21600,
    description: "Model deprecation and effective date documentation.",
  },
  {
    id: "anthropic-news",
    vendor: "anthropic",
    name: "Anthropic News RSS",
    url: "https://www.anthropic.com/news/rss.xml",
    parser: "rss_atom",
    defaultCategory: "blog_update",
    cooldownSeconds: 3600,
    description: "Anthropic company and model announcements.",
  },
  {
    id: "anthropic-releases",
    vendor: "anthropic",
    name: "Anthropic Release Notes",
    url: "https://www.anthropic.com/engineering/feed",
    parser: "rss_atom",
    defaultCategory: "release_note",
    cooldownSeconds: 7200,
    description: "Anthropic engineering updates and changelogs.",
  },
  {
    id: "anthropic-github-releases",
    vendor: "anthropic",
    name: "Anthropic GitHub Releases",
    url: "https://github.com/anthropics/anthropic-sdk-python/releases.atom",
    parser: "github_releases",
    defaultCategory: "model_release",
    cooldownSeconds: 10800,
    description: "Official Anthropic SDK release announcements.",
  },
  {
    id: "anthropic-model-deprecations",
    vendor: "anthropic",
    name: "Anthropic Deprecation Docs",
    url: "https://docs.anthropic.com/en/docs/resources/model-deprecations",
    parser: "docs_html",
    defaultCategory: "deprecation",
    cooldownSeconds: 21600,
    description: "Canonical deprecation timeline for Anthropic services and models.",
  },
  {
    id: "google-ai-blog-rss",
    vendor: "google",
    name: "Google AI Blog RSS",
    url: "https://ai.googleblog.com/feeds/posts/default?alt=rss",
    parser: "rss_atom",
    defaultCategory: "blog_update",
    cooldownSeconds: 3600,
    description: "Google AI Blog and Gemini announcements.",
  },
  {
    id: "google-gemini-release-notes-rss",
    vendor: "google",
    name: "Google Gemini SDK Releases",
    url: "https://github.com/google-gemini/generative-ai-js/releases.atom",
    parser: "github_releases",
    defaultCategory: "release_note",
    cooldownSeconds: 10800,
    description: "Official Google Gemini SDK release feed.",
  },
  {
    id: "google-vertex-release-notes",
    vendor: "google",
    name: "Vertex AI Release Notes",
    url: "https://cloud.google.com/feeds/vertexai-release-notes.rss",
    parser: "changelog_html",
    defaultCategory: "release_note",
    cooldownSeconds: 7200,
    description: "Google Vertex AI release notes and availability updates.",
  },
  {
    id: "google-cloud-ai-release-notes",
    vendor: "google",
    name: "Google Cloud AI/ML Release Notes",
    url: "https://cloud.google.com/feeds/machine-learning-release-notes.rss",
    parser: "changelog_html",
    defaultCategory: "release_note",
    cooldownSeconds: 7200,
    description: "Google Cloud AI and ML release updates.",
  },
];
