import type { SourceManifestEntry } from "../types.js";

export const sourceManifest: SourceManifestEntry[] = [
  {
    id: "openai-blog-rss",
    vendor: "openai",
    name: "OpenAI Blog RSS",
    url: "https://openai.com/news/rss.xml",
    parser: "rss_atom",
    defaultCategory: "blog_update",
    cooldownSeconds: 3600,
    description: "OpenAI news and product updates.",
  },
  {
    id: "openai-platform-release-notes-rss",
    vendor: "openai",
    name: "OpenAI Platform Changelog RSS",
    url: "https://platform.openai.com/changelog.rss",
    parser: "rss_atom",
    defaultCategory: "release_note",
    cooldownSeconds: 3600,
    description: "OpenAI platform release notes and changelog posts.",
  },
  {
    id: "openai-github-releases",
    vendor: "openai",
    name: "OpenAI SDK Releases",
    url: "https://github.com/openai/openai-python/releases.atom",
    parser: "github_releases",
    defaultCategory: "model_release",
    cooldownSeconds: 10800,
    description: "Official repository releases for OpenAI SDK components.",
  },
  {
    id: "openai-model-release-notes",
    vendor: "openai",
    name: "OpenAI Model Deprecations",
    url: "https://platform.openai.com/docs/deprecations",
    parser: "changelog_html",
    defaultCategory: "deprecation",
    cooldownSeconds: 21600,
    description: "Model deprecation and effective date documentation.",
  },
  {
    id: "anthropic-news",
    vendor: "anthropic",
    name: "Anthropic News RSS",
    url: "https://www.anthropic.com/news/rss.xml",
    parser: "rss_atom",
    defaultCategory: "blog_update",
    cooldownSeconds: 3600,
    description: "Anthropic company and model announcements.",
  },
  {
    id: "anthropic-releases",
    vendor: "anthropic",
    name: "Anthropic Release Notes",
    url: "https://www.anthropic.com/engineering/feed",
    parser: "rss_atom",
    defaultCategory: "release_note",
    cooldownSeconds: 7200,
    description: "Anthropic engineering updates and changelogs.",
  },
  {
    id: "anthropic-github-releases",
    vendor: "anthropic",
    name: "Anthropic GitHub Releases",
    url: "https://github.com/anthropics/anthropic-sdk-python/releases.atom",
    parser: "github_releases",
    defaultCategory: "model_release",
    cooldownSeconds: 10800,
    description: "Official Anthropic SDK release announcements.",
  },
  {
    id: "anthropic-model-deprecations",
    vendor: "anthropic",
    name: "Anthropic Deprecation Docs",
    url: "https://docs.anthropic.com/en/docs/resources/model-deprecations",
    parser: "docs_html",
    defaultCategory: "deprecation",
    cooldownSeconds: 21600,
    description: "Canonical deprecation timeline for Anthropic services and models.",
  },
  {
    id: "google-ai-blog-rss",
    vendor: "google",
    name: "Google Gemini Blog RSS",
    url: "https://blog.google/products-and-platforms/products/gemini/rss/",
    parser: "rss_atom",
    defaultCategory: "blog_update",
    cooldownSeconds: 3600,
    description: "Official Google Blog feed for Gemini announcements and model posts.",
  },
  {
    id: "google-gemini-release-notes-rss",
    vendor: "google",
    name: "Google Gen AI JS SDK Releases",
    url: "https://github.com/googleapis/js-genai/releases.atom",
    parser: "github_releases",
    defaultCategory: "release_note",
    cooldownSeconds: 10800,
    description: "Official Google Gen AI JavaScript SDK release feed.",
  },
  {
    id: "google-vertex-release-notes",
    vendor: "google",
    name: "Vertex Generative AI Release Notes",
    url: "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/release-notes?hl=en",
    parser: "google_vertex_release_notes_html",
    defaultCategory: "release_note",
    cooldownSeconds: 7200,
    description: "Generative AI on Vertex AI release notes for Gemini, Veo, and Imagen.",
  },
  {
    id: "google-cloud-ai-release-notes",
    vendor: "google",
    name: "Google Gemini API Changelog",
    url: "https://ai.google.dev/gemini-api/docs/changelog?hl=en",
    parser: "google_gemini_api_html",
    defaultCategory: "release_note",
    cooldownSeconds: 7200,
    description: "Official Gemini API changelog with model launches, rollouts, and deprecations.",
  },
];
